// Auto-generated by scripts/fetch-avatars.mjs — do not hand-edit.
export const AVATARS: Record<string, { ig?: string; li?: string }> = {
  "gary-vee": {
    "li": "/avatars/gary-vee-li.jpg"
  },
  "simon-sinek": {
    "li": "/avatars/simon-sinek-li.jpg"
  },
  "tim-ferriss": {
    "li": "/avatars/tim-ferriss-li.jpg"
  },
  "brene-brown": {
    "li": "/avatars/brene-brown-li.jpg"
  },
  "mel-robbins": {
    "li": "/avatars/mel-robbins-li.jpg"
  },
  "sara-blakely": {
    "li": "/avatars/sara-blakely-li.jpg"
  },
  "jay-shetty": {
    "li": "/avatars/jay-shetty-li.jpg"
  },
  "alexis-ohanian": {
    "li": "/avatars/alexis-ohanian-li.jpg"
  },
  "whitney-wolfe": {
    "li": "/avatars/whitney-wolfe-li.jpg"
  },
  "serena-williams": {},
  "sophia-amoruso": {
    "li": "/avatars/sophia-amoruso-li.jpg"
  },
  "marques-brownlee": {
    "li": "/avatars/marques-brownlee-li.jpg"
  },
  "adam-grant": {
    "li": "/avatars/adam-grant-li.jpg"
  },
  "bill-gates": {},
  "leila-hormozi": {},
  "alex-hormozi": {
    "li": "/avatars/alex-hormozi-li.jpg"
  },
  "emma-grede": {},
  "steven-bartlett": {},
  "melinda-gates": {},
  "codie-sanchez": {},
  "richard-branson": {
    "li": "/avatars/richard-branson-li.jpg"
  },
  "casey-neistat": {
    "li": "/avatars/casey-neistat-li.jpg"
  },
  "chris-williamson": {},
  "arianna-huffington": {},
  "bozoma-saint-john": {}
};
